# Generated by Django 3.2.3 on 2021-06-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AniversarioAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_participante', models.CharField(max_length=100, verbose_name='Nombre y Apellidos')),
                ('creacion_cert', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('codigo_udh', models.CharField(max_length=100, null=True, verbose_name='CODIGO UDH')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='email')),
                ('validation_code', models.CharField(max_length=100, null=True, verbose_name='Número de validación')),
            ],
            options={
                'verbose_name': 'Aniversario Ambiente',
            },
        ),
        migrations.CreateModel(
            name='ConferenciaInternacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_participante', models.CharField(max_length=100, verbose_name='Nombre y Apellidos')),
                ('creacion_cert', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('dni', models.CharField(max_length=100, null=True, verbose_name='DNI')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='email')),
                ('celular', models.CharField(max_length=100, null=True, verbose_name='celular')),
                ('pais', models.CharField(max_length=100, null=True, verbose_name='pais')),
                ('universidad', models.CharField(max_length=100, null=True, verbose_name='Universidad')),
                ('carrera', models.CharField(max_length=100, null=True, verbose_name='Escuela')),
                ('evento', models.CharField(max_length=100, null=True)),
                ('validation_code', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Conferencia Internacional',
            },
        ),
        migrations.CreateModel(
            name='Des_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_participante', models.CharField(max_length=100, verbose_name='Nombre y Apellidos')),
                ('creacion_cert', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Usuario')),
                ('dni', models.CharField(max_length=100, null=True, verbose_name='DNI')),
                ('evento', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Desarrollo & Logistica',
            },
        ),
        migrations.CreateModel(
            name='Innova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_participante', models.CharField(max_length=100, verbose_name='Nombre y Apellidos')),
                ('creacion_cert', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Usuario')),
                ('dni', models.CharField(max_length=100, null=True, verbose_name='DNI')),
                ('carrera', models.CharField(max_length=100, null=True, verbose_name='Carrera')),
                ('evento', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Innova 62',
            },
        ),
        migrations.CreateModel(
            name='Mentore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mentor', models.CharField(max_length=100, verbose_name='Nombre y Apellidos')),
                ('creacion_cert', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Usuario')),
                ('dni', models.CharField(max_length=100, null=True, verbose_name='DNI')),
                ('evento', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ponentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ponente', models.CharField(max_length=100, verbose_name='Nombre y Apellidos')),
                ('creacion_cert', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Usuario')),
                ('dni', models.CharField(max_length=100, null=True, verbose_name='DNI')),
                ('evento', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=100, verbose_name='Nombre y Apellidos')),
                ('creacion_cert', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Usuario')),
                ('dni', models.CharField(max_length=100, null=True, verbose_name='DNI')),
                ('carrera', models.CharField(max_length=100, null=True, verbose_name='Carrera')),
                ('evento', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Innovation Challenge',
            },
        ),
        migrations.CreateModel(
            name='RegistroGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_participante', models.CharField(max_length=100, null=True, verbose_name='Nombre y Apellidos')),
                ('creacion_cert', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('codigo_estudiante', models.CharField(max_length=100, null=True, verbose_name='Codigo UDH')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='email')),
                ('celular', models.CharField(max_length=100, null=True, verbose_name='Celular')),
                ('carrera', models.CharField(max_length=100, null=True, verbose_name='Carrera')),
                ('evento', models.CharField(max_length=100, null=True, verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Registro General',
            },
        ),
    ]
