# Generated by Django 3.2.3 on 2021-06-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferenciainternacional',
            options={'verbose_name': 'BINDIN'},
        ),
        migrations.RemoveField(
            model_name='conferenciainternacional',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='conferenciainternacional',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='conferenciainternacional',
            name='universidad',
        ),
        migrations.RemoveField(
            model_name='conferenciainternacional',
            name='validation_code',
        ),
    ]
