# Generated by Django 3.2.3 on 2021-06-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen', '0002_auto_20210622_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bindin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_participante', models.CharField(max_length=100, verbose_name='Nombre y Apellidos')),
                ('creacion_cert', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('dni', models.CharField(max_length=100, null=True, verbose_name='DNI')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='email')),
                ('pais', models.CharField(max_length=100, null=True, verbose_name='pais')),
                ('evento', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
