# Generated by Django 3.2.3 on 2021-07-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen', '0003_bindin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AniversarioAmbientalDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente_nombre', models.CharField(max_length=50, null=True, verbose_name='Nombre Docente')),
                ('dni', models.CharField(max_length=50, null=True, verbose_name='dni')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Aniversario Ambiental ORGANIZADORES',
                'verbose_name_plural': 'Aniversario Ambiental ORGANIZADORES',
            },
        ),
        migrations.AlterModelOptions(
            name='conferenciainternacional',
            options={'verbose_name': 'Semillero Internacional'},
        ),
    ]
