# Generated by Django 3.2.3 on 2021-07-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen', '0004_auto_20210703_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenciaInternacionalOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizador', models.CharField(max_length=100, null=True, verbose_name='Nombre y Apellidos')),
                ('dni', models.CharField(max_length=100, null=True, verbose_name='dni')),
                ('universidad', models.CharField(max_length=100, null=True, verbose_name='universidad')),
            ],
            options={
                'verbose_name': 'Semillero Internacional',
                'verbose_name_plural': 'Semillero Internacional - ORGANIZADORES',
            },
        ),
        migrations.AlterModelOptions(
            name='aniversarioambiente',
            options={'verbose_name': 'Aniversario Ambiente', 'verbose_name_plural': 'Aniversario Ambiental ALUMNOS'},
        ),
        migrations.AlterModelOptions(
            name='conferenciainternacional',
            options={'verbose_name': 'Semillero Internacional', 'verbose_name_plural': 'Semillero Internacional - PARTICIPANTES'},
        ),
    ]
