# Generated by Django 3.2.3 on 2021-07-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen', '0005_auto_20210706_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_participante', models.CharField(max_length=100, null=True, verbose_name='Nombre Participante')),
                ('dni', models.CharField(max_length=100, null=True, verbose_name='dni o código de alumno')),
                ('correo', models.CharField(max_length=100, null=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Eco Creatividad - ASISTENCIA',
                'verbose_name_plural': 'Eco Creatividad - ASISTENCIA',
            },
        ),
        migrations.CreateModel(
            name='EcoConcurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_participante', models.CharField(max_length=100, null=True, verbose_name='Nombre Participante')),
                ('dni', models.CharField(max_length=100, null=True, verbose_name='dni o código de alumno')),
                ('correo', models.CharField(max_length=100, null=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Eco Creatividad',
                'verbose_name_plural': 'Eco Creatividad',
            },
        ),
    ]
