# Generated by Django 3.2.3 on 2021-07-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen', '0007_auto_20210716_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bindin',
        ),
        migrations.DeleteModel(
            name='RegistroGeneral',
        ),
    ]
