# Generated by Django 3.2.3 on 2021-07-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen', '0008_auto_20210716_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecoconcurso',
            options={'verbose_name': 'Eco Creatividad - BBDD', 'verbose_name_plural': 'Eco Creatividad - BBDD'},
        ),
    ]
